databases:
  - name: cojari
    databaseName: cojari_prod
    user: cojari_user

services:
  - type: web
    name: cojari
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cojari
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false